### ISSUE TITLE
コード修正

### ISSUE THREAD

**Issue by IceSword8492** [IceSword8492/jikkenb_laravel#7]
# 修正対象

## バグ

https://github.com/IceSword8492/jikkenb_laravel/blob/51b9bd23d0b403ea8f377071941102b8713666d7/app/Http/Controllers/ConfirmController.php#L30

## 安全性

https://github.com/IceSword8492/jikkenb_laravel/blob/5466a44cda4900f5c2f31021e0e39dcc114d1b5e/app/Http/Controllers/RegisterController.php#L17

https://github.com/IceSword8492/jikkenb_laravel/blob/51b9bd23d0b403ea8f377071941102b8713666d7/app/Http/Controllers/ConfirmController.php#L18-L23

https://github.com/IceSword8492/jikkenb_laravel/blob/51b9bd23d0b403ea8f377071941102b8713666d7/app/Http/Controllers/ConfirmController.php#L25

https://github.com/IceSword8492/jikkenb_laravel/blob/51b9bd23d0b403ea8f377071941102b8713666d7/app/Http/Controllers/ConfirmController.php#L31

https://github.com/IceSword8492/jikkenb_laravel/blob/51b9bd23d0b403ea8f377071941102b8713666d7/app/Http/Controllers/AuthController.php#L15-L16

## 不要

https://github.com/IceSword8492/jikkenb_laravel/blob/5466a44cda4900f5c2f31021e0e39dcc114d1b5e/app/Http/Controllers/RegisterController.php#L32

**Comment by Tsky-dusk** [comment]
バグと不要については直しておきます
安全性に関してはお手上げです…

**Comment by IceSword8492** [comment]
`$request->query`, `$request->input`からデータを撮るときは変数に値が入っていない場合があるから取得したあとに空かチェックして空だったら`['success' => false]`を返す。

SQL文に直接変数を文字列結合でつなげると不具合のもとになるからprepare, executeを使う。

issetで分岐してるやつはifの条件式がfalseになった場合に$id, $tokenが宣言されない状態で処理が続行されてあとで$id, $tokenを呼んだときにundefined系のエラーが出るはずだからelse文で`['success' => false]`を返す。
